// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: usercenter.proto

package server

import (
	"context"

	"go-zero-flash-sale/app/usercenter/cmd/rpc/internal/logic"
	"go-zero-flash-sale/app/usercenter/cmd/rpc/internal/svc"
	"go-zero-flash-sale/app/usercenter/cmd/rpc/usercenter"
)

type UserCenterServiceServer struct {
	svcCtx *svc.ServiceContext
	usercenter.UnimplementedUserCenterServiceServer
}

func NewUserCenterServiceServer(svcCtx *svc.ServiceContext) *UserCenterServiceServer {
	return &UserCenterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServiceServer) Login(ctx context.Context, in *usercenter.LoginRequest) (*usercenter.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServiceServer) Register(ctx context.Context, in *usercenter.RegisterRequest) (*usercenter.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServiceServer) GetUserInfo(ctx context.Context, in *usercenter.GetUserInfoRequest) (*usercenter.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserCenterServiceServer) GetUserAuthByAuthKey(ctx context.Context, in *usercenter.GetUserAuthByAuthKeyRequest) (*usercenter.GetUserAuthByAuthKeyResponse, error) {
	l := logic.NewGetUserAuthByAuthKeyLogic(ctx, s.svcCtx)
	return l.GetUserAuthByAuthKey(in)
}

func (s *UserCenterServiceServer) GetUserAuthByUserId(ctx context.Context, in *usercenter.GetUserAuthByUserIdRequest) (*usercenter.GetUserAuthByUserIdResponse, error) {
	l := logic.NewGetUserAuthByUserIdLogic(ctx, s.svcCtx)
	return l.GetUserAuthByUserId(in)
}

func (s *UserCenterServiceServer) GenerateToken(ctx context.Context, in *usercenter.GenerateTokenRequest) (*usercenter.GenerateTokenResponse, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}
