// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: usercenter.proto

package usercenterservice

import (
	"context"

	"go-zero-flash-sale/app/usercenter/cmd/rpc/usercenter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateTokenRequest         = usercenter.GenerateTokenRequest
	GenerateTokenResponse        = usercenter.GenerateTokenResponse
	GetUserAuthByAuthKeyRequest  = usercenter.GetUserAuthByAuthKeyRequest
	GetUserAuthByAuthKeyResponse = usercenter.GetUserAuthByAuthKeyResponse
	GetUserAuthByUserIdRequest   = usercenter.GetUserAuthByUserIdRequest
	GetUserAuthByUserIdResponse  = usercenter.GetUserAuthByUserIdResponse
	GetUserInfoRequest           = usercenter.GetUserInfoRequest
	GetUserInfoResponse          = usercenter.GetUserInfoResponse
	LoginRequest                 = usercenter.LoginRequest
	LoginResponse                = usercenter.LoginResponse
	RegisterRequest              = usercenter.RegisterRequest
	RegisterResponse             = usercenter.RegisterResponse
	User                         = usercenter.User
	UserAuth                     = usercenter.UserAuth

	UserCenterService interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		GetUserAuthByAuthKey(ctx context.Context, in *GetUserAuthByAuthKeyRequest, opts ...grpc.CallOption) (*GetUserAuthByAuthKeyResponse, error)
		GetUserAuthByUserId(ctx context.Context, in *GetUserAuthByUserIdRequest, opts ...grpc.CallOption) (*GetUserAuthByUserIdResponse, error)
		GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	}

	defaultUserCenterService struct {
		cli zrpc.Client
	}
)

func NewUserCenterService(cli zrpc.Client) UserCenterService {
	return &defaultUserCenterService{
		cli: cli,
	}
}

func (m *defaultUserCenterService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := usercenter.NewUserCenterServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserCenterService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := usercenter.NewUserCenterServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserCenterService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := usercenter.NewUserCenterServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserCenterService) GetUserAuthByAuthKey(ctx context.Context, in *GetUserAuthByAuthKeyRequest, opts ...grpc.CallOption) (*GetUserAuthByAuthKeyResponse, error) {
	client := usercenter.NewUserCenterServiceClient(m.cli.Conn())
	return client.GetUserAuthByAuthKey(ctx, in, opts...)
}

func (m *defaultUserCenterService) GetUserAuthByUserId(ctx context.Context, in *GetUserAuthByUserIdRequest, opts ...grpc.CallOption) (*GetUserAuthByUserIdResponse, error) {
	client := usercenter.NewUserCenterServiceClient(m.cli.Conn())
	return client.GetUserAuthByUserId(ctx, in, opts...)
}

func (m *defaultUserCenterService) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	client := usercenter.NewUserCenterServiceClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}
